package alvaro.horasextras_productoshigiene_lectorficheros;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class LectorFicheros extends javax.swing.JFrame {

    File f;
    BufferedReader br;
    
    public LectorFicheros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lRuta = new javax.swing.JLabel();
        tRuta = new javax.swing.JTextField();
        bAbrir = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        bLeer = new javax.swing.JButton();
        lSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lRuta.setText("Nombre o ruta");

        bAbrir.setText("ABRIR");
        bAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirActionPerformed(evt);
            }
        });

        bCerrar.setText("CERRAR");
        bCerrar.setEnabled(false);
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        bLeer.setText("LEER LÍNEA");
        bLeer.setEnabled(false);
        bLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLeerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tRuta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAbrir)
                                .addGap(18, 18, 18)
                                .addComponent(bCerrar)))
                        .addGap(18, 18, 18)
                        .addComponent(bLeer)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCerrar)
                    .addComponent(bAbrir)
                    .addComponent(bLeer))
                .addGap(30, 30, 30)
                .addComponent(lSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Lector ficheros");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirActionPerformed
        f = new File(tRuta.getText());
        if (f.exists()) {
            bLeer.setEnabled(true);
            bCerrar.setEnabled(true);
            bAbrir.setEnabled(false);
            lRuta.setEnabled(false);
            try {
                br = new BufferedReader(new FileReader(f));
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el fichero");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Error al encontrar el fichero");
            tRuta.setText("");
        }    
    }//GEN-LAST:event_bAbrirActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        try {
            br.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al cerrar el fichero");
        }
        bLeer.setEnabled(false);
        bCerrar.setEnabled(false);
        bAbrir.setEnabled(true);
        lRuta.setEnabled(true);
        tRuta.setText("");
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLeerActionPerformed
        String text;
        try {
            text = br.readLine();
            if (text == null) {
                JOptionPane.showMessageDialog(this, "Fin del fichero");
                bLeer.setEnabled(false);
            }
            lSalida.setText(text);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el fichero");
        }
    }//GEN-LAST:event_bLeerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LectorFicheros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LectorFicheros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LectorFicheros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LectorFicheros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectorFicheros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrir;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bLeer;
    private javax.swing.JLabel lRuta;
    private javax.swing.JLabel lSalida;
    private javax.swing.JTextField tRuta;
    // End of variables declaration//GEN-END:variables
}
