package alvaro.simulacro;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ContadorPulsaciones extends javax.swing.JFrame {
    private int pulso1 = 0;
    private int pulso2 = 0;
    private File f;
    private PrintWriter pw;
    
    
    private ContadorPulsaciones(){
        initComponents();
        f = new File("pulsaciones.txt");
        if (!f.exists()) {
            try {
                f.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error con  el archivo");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        bBoton1 = new javax.swing.JButton();
        bBoton2 = new javax.swing.JButton();
        lB1 = new javax.swing.JLabel();
        lB2 = new javax.swing.JLabel();
        bRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contador pulsaciones");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pFondo.setBackground(new java.awt.Color(204, 204, 204));
        pFondo.setToolTipText("");

        bBoton1.setText("Botón 1");
        bBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoton1ActionPerformed(evt);
            }
        });

        bBoton2.setText("Botón 2");
        bBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoton2ActionPerformed(evt);
            }
        });

        lB1.setText("Botón 1: 0 veces");

        lB2.setText("Botón 2: 0 veces");

        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(bBoton1))
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lB1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(bBoton2))
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lB2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(bRegistrar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lB1)
                    .addComponent(lB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBoton1)
                    .addComponent(bBoton2))
                .addGap(35, 35, 35)
                .addComponent(bRegistrar)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoton1ActionPerformed
        pulso1++;
        lB1.setText("Botón 1: " + pulso1 + " veces");
    }//GEN-LAST:event_bBoton1ActionPerformed

    private void bBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoton2ActionPerformed
        pulso2++;
        lB2.setText("Botón 2: " + pulso2 + " veces");
    }//GEN-LAST:event_bBoton2ActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        try {
            pw = new PrintWriter(new FileWriter(f, true));
            pw.println(Calendar.getInstance().getTime().toString() + ';' + pulso1 + ';' + pulso2);
            pw.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se puede escribir en el archivo");
        }
        lB1.setText("Botón 1: 0 veces");
        lB2.setText("Botón 2: 0 veces");
        pulso1 = 0;
        pulso2 = 0;
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorPulsaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorPulsaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorPulsaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorPulsaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorPulsaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBoton1;
    private javax.swing.JButton bBoton2;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JLabel lB1;
    private javax.swing.JLabel lB2;
    private javax.swing.JPanel pFondo;
    // End of variables declaration//GEN-END:variables

    
}
